### ISSUE TITLE
Printer Connection

### ISSUE THREAD

**Issue by the-pat** [the-pat/WcoeJobFairRegistration#19]
The application shouldn't try connecting to a printer until `Print` is selected.

If the application is started before the printer is plugged into the computer, then the application never connects to the printer.

- [x] Attempt a printer connection on application startup
- [x] Check printer connection when `Print` is selected, attempt connection if there is no printer connected
- [x] Notify the user if no printer is connected

**Comment by frankibem** [comment]
Can also be a good thing to inform operator that printer needs to be connected. We can try to connect on startup as well as when print is selected.

**Comment by the-pat** [comment]
Good point. I've updated the issue.
